# Generated by Django 5.0 on 2023-12-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=128)),
                ("contact", models.CharField(max_length=128)),
                ("headoffice", models.CharField(max_length=128)),
            ],
        ),
    ]
