# Generated by Django 5.0 on 2023-12-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brand", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="contact",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="brand",
            name="email",
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="brand",
            name="headoffice",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
