# Generated by Django 5.0 on 2023-12-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brand", "0002_alter_brand_contact_alter_brand_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
