# Generated by Django 5.0 on 2023-12-10 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brand", "0003_alter_brand_id"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="brand",
            table="brand_management",
        ),
    ]
