# Generated by Django 5.0 on 2023-12-10 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_category_id"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="category_management",
        ),
        migrations.AlterModelTable(
            name="product",
            table="product_management",
        ),
    ]
